name: Build, Test and Publish

permissions: read-all

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]


env:
  MYSQL_HOST: ${{ vars.MYSQL_HOST }}
  MYSQL_USER: ${{ vars.MYSQL_USER }}
  MYSQL_ROOT_PASSWORD: ${{ vars.MYSQL_PASSWORD }}
  MYSQL_TCP_PORT: 3306
  # MYSQL_PORT: ${{ vars.MYSQL_PORT }}
  MYSQL_DATABASE: ${{vars.MYSQL_DBNAME }}
  POSTGRESQL_HOST: ${{ vars.POSTGRESQL_HOST }}
  PGUSER: ${{ vars.POSTGRESQL_USER }}
  POSTGRES_DB: ${{ vars.POSTGRESQL_USER }}
  POSTGRES_PASSWORD: ${{ vars.POSTGRESQL_PASSWORD }}
  # POSTGRESQL_PORT: ${{ vars.POSTGRESQL_PORT }}
  SQLSERVER_HOST: ${{ vars.SQLSERVER_HOST }}
  SQLSERVER_USER: sa
  SA_PASSWORD: ${{ vars.SQLSERVER_PASSWORD }}
  # SQLSERVER_PORT: ${{ vars.SQLSERVER_PORT }}
  MONGO_HOST: ${{ vars.MONGO_HOST }}
  MONGO_INITDB_ROOT_USERNAME: ${{ vars.MONGO_USER }}
  MONGO_INITDB_ROOT_PASSWORD: ${{ vars.MONGO_PASSWORD }}
  # MONGO_PORT: ${{ vars.MONGO_PORT }}
  ACCEPT_EULA: Y

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env << EOF
          MONGO_HOST=${{ vars.MONGO_HOST }}
          MONGO_INITDB_ROOT_USERNAME=${{ vars.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD=${{ vars.MONGO_PASSWORD }}
          MONGO_PORT=27017
          MYSQL_DATABASE=${{ vars.MYSQL_DBNAME }}
          MYSQL_HOST=${{ vars.MYSQL_HOST }}
          MYSQL_ROOT_PASSWORD=${{ vars.MYSQL_PASSWORD }}
          MYSQL_TCP_PORT=3306
          POSTGRESQL_HOST=${{ vars.POSTGRESQL_HOST }}
          POSTGRES_PASSWORD=${{ vars.POSTGRESQL_PASSWORD }}
          POSTGRESQL_PORT=5432
          PGUSER=${{ vars.POSTGRESQL_USER }}
          POSTGRES_DB=${{ vars.POSTGRESQL_USER }}
          SQLSERVER_HOST=${{ vars.SQLSERVER_HOST }}
          SA_PASSWORD=${{ vars.SQLSERVER_PASSWORD }}
          SQLSERVER_PORT=1433
          SQLSERVER_USER=sa
          ACCEPT_EULA=Y
          EOF

      - name: Install uv
        uses: astral-sh/setup-uv@main
        # with:
          # version: "0.6.12"

      - name: Docker Compose
        uses: hoverkraft-tech/compose-action@main
        with:
          compose-file: compose.yaml

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Test code quality, coverage and generate documentation
        run: |
          ./pipeline.sh
          uv run coverage xml -o coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - if: ${{ github.event_name == 'pull_request' && matrix.python-version == 3.13 }}
        name: Publish to Test Pypi
        run: |
          uv build
          uv publish --token ${{ secrets.TEST_PYPI_TOKEN }} --index testpypi

      - if: ${{ github.event_name == 'push' && matrix.python-version == 3.13 }}
        name: Publish to Pypi
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_TOKEN }}
